version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  dev-content-nginx:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./nginx/dev-content.conf:/etc/nginx/conf.d/default.conf
      - ../staging-content:/usr/share/nginx/html
  minio:
    image: minio/minio:latest
    entrypoint: sh
    ports:
      - "9000:9000"
      - "9001:9001"
    command: -c 'minio server --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      exit 0;
      "

volumes:
  db-data:
  minio-data:
