/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Uuid = string;
export type LessonPath = string;

export interface Course {
  id: Uuid;
  title: string;
  description: string;
  lessons: LessonPath[];
}
